
replicaCount: 2

image:
  repository: 058264552037.dkr.ecr.ap-southeast-2.amazonaws.com/esoft-springboot
  tag: latest
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: LoadBalancer
  port: 8080

ingress:
  enabled: true
  annotations: {}
  paths: []
  hosts:
    - chart-example.local
  tls: []

resources: {}

nodeSelector: {}

tolerations: []

affinity: {}